pconnectacc/urls.py
from django.contrib import admin
from django.urls import path, include
from taskcontrol import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task-control/', include('taskcontrol.urls')),
]

taskcontrol/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = "taskcontrol"

handler404 = 'taskcontrol.views.error_404_view'

urlpatterns = [
    path('eror404/', error_404_view, name='eror404'),
    path('coding/', building_code, name='building_code'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    # path('test/', testpage, name='testpage'),
    path('get_districts/', get_districts, name='GetDistrict'),
    path('get_subdistricts/', get_subdistricts, name='GetSubdistrict'),
    path('gen_engagement_code_auto/', gen_engagement_code_auto, name='get_latest_job_code'),
    path('get_channel/', get_channel, name='get_channel'),

    path('get_engagement_type/', get_engagement_type, name='get_engagement_type'),
    path('api/get_engagement_details/', get_engagement_details, name='get_engagement_details'),



    path('client/list/', client_list, name='client_list'),
    path('client/<int:client_id>/', record_client, name='record_client'),

    path('client/create/', client_create, name='client_create'),
    path('client/detail/<int:client_id>/', client_detail, name='client_detail'),
    path('client/update/<int:client_id>/', client_update, name='client_update'),
    path('client/delete/<int:client_id>/', client_delete, name='client_delete'),

    path('client/contact_create/<int:client_id>/', create_contact, name='create_contact'),
    path('client/contact_delete/<int:contact_id>/', delete_contact, name='delete_contact'),

    path('client/password/<int:client_id>/', password_list, name='password_list'),
    path('client/password_create/<int:client_id>/', create_password, name='create_password'),
    path('client/password_update/<int:password_id>/', update_password, name='update_password'),
    path('client/password_delete/<int:password_id>/', delete_password, name='delete_password'),

    path('client/file_list/<int:client_id>/', file_client_list, name='file_client_list'),
    path('client/file_create/<int:client_id>/', file_client_create, name='file_client_create'),
    path('client/file_delete/<int:file_id>/', file_client_delete, name='file_client_delete'),
    path('client/file_client_download_file/<int:file_id>/', file_client_download_file, name='file_client_download_file'),
    path('client/file_client_download_image/<int:image_id>/', file_client_download_image, name='file_client_download_image'),

    path('engagement/list/', engagement_list, name='engagement_list'),
    path('engagement/create/', engagement_create, name='engagement_create'),
    path('engagement/<int:engagement_id>/', record_engagement, name='record_engagement'),
    path('engagement/detail/<int:engagement_id>/', engagement_detail, name='engagement_detail'),
    path('engagement/update/<int:engagement_id>/', engagement_update, name='engagement_update'),
    path('engagement/delete/<int:engagement_id>/', engagement_delete, name='engagement_delete'),

    path('engagement/detail_job/<int:engagement_id>/', engagement_job, name='engagement_job'),
    path('engagement/detail_job/create/<int:engagement_id>/', engagement_job_create, name='engagement_job_create'),
    path('engagement/detail_job/delete/<int:engagement_job_id>/', engagement_job_delete, name='engagement_job_delete'),

    path('engagement/file_list/<int:engagement_id>/', file_engagement_list, name='file_engagement_list'),
    path('engagement/file_create/<int:engagement_id>/', file_engagement_create, name='file_engagement_create'),
    path('engagement/file_delete/<int:file_id>/', file_engagement_delete, name='file_engagement_delete'),
    path('engagement/file_client_download_file/<int:file_id>/', download_file_engagement, name='download_file_engagement'),
    path('engagement/file_client_download_image/<int:image_id>/', download_image_engagement, name='download_image_engagement'),

    path('manage_category/', manage_category, name='manage_category'),
    path('manage_category/update/<int:category_id>/', update_category, name='update_category'),
    path('manage_category/delete/<int:category_id>/', delete_category, name='delete_category'),

    path('manage_type/', manage_type, name='manage_type'),
    path('manage_type/update/<int:type_id>/', update_type, name='update_type'),
    path('manage_type/delete/<int:type_id>/', delete_type, name='delete_type'),

    path('manage_channel/', manage_channel, name='manage_channel'),
    path('manage_channel/update/<int:channel_id>/', update_channel, name='update_channel'),
    path('manage_channel/delete/<int:channel_id>/', delete_channel, name='delete_channel'),

    path('manage_register_type/', manage_register_type, name='manage_register_type'),
    path('manage_register_type/update/<int:register_type_id>/', update_register_type, name='update_register_type'),
    path('manage_register_type/delete/<int:register_type_id>/', delete_register_type, name='delete_register_type'),

    path('kanban_board/', kanban_board, name='kanban_board'),
    path('update_engagement_detail_status', update_engagement_detail_status, name='update_engagement_detail_status'),
    path('update_task_status', update_task_status, name='update_task_status'),
    path('add_new_task/', add_new_task, name='add_new_task'),

    path('kanban_board_filter/', kanban_board_filter, name='kanban_board_filter'),
    path('get_status_counts/', get_status_counts, name='get_status_counts'),
    path('update_near_deadline/', update_near_deadline, name='update_near_deadline'),
    path('get_date_deadlines/', get_date_deadlines, name='get_date_deadlines'),

    
    path('update_engagement_detail_comment', update_engagement_detail_comment, name='update_engagement_detail_comment'),
    path('search_filter_engagement_details/', search_filter_engagement_details, name='search_filter_engagement_details'),
    path('get_filter_engagement_details/', get_filter_engagement_details, name='get_filter_engagement_details'),

    path('dashboard/', dashboard, name='dashboard'),
    path('api/engagement-details/', get_engagement_detail_dashboard, name='get_engagement_detail_dashboard'),
    # path('search_datatable/', search_datatable, name='search_datatable'),
    path('get_engagement_detail_status/', get_engagement_detail_status, name='get_engagement_detail_status'),
    path('get_accounting/', get_accounting, name='get_accounting'),
    path('get_tax/', get_tax, name='get_tax'),
    path('get_payroll/', get_payroll, name='get_payroll'),
    path('get_report/', get_report, name='get_report'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskcontrol/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.db import models
from taskcontrol.models import FileManage

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254)

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

taskcontrol/views.py
from django.shortcuts import render, redirect, get_object_or_404
from taskcontrol.models import *
from .forms import CustomUserCreationForm, CustomPasswordResetForm
from datetime import datetime, date, timedelta
from django.utils import timezone
from django.contrib import messages
from django.db import transaction
from django.utils.dateparse import parse_date
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseBadRequest, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.db.models import Max, Count, F, Subquery, Q, Case, When, Value, CharField, Prefetch
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from collections import Counter
from django.views.decorators.http import require_POST
from dateutil.relativedelta import relativedelta
from django.views.decorators.csrf import csrf_exempt
from django.db.models.functions import ExtractMonth, ExtractYear
import json


# Constants
STATUS_OPEN_JOB = ('OPEN_JOB', 'PENDING_CLIENT', 'REVIEW', 'IN_PROGRESS')
STATUS_DONE = ('DONE',)

#TODO Error404
def error_404_view(request, exception):
    return render(request, 'task/eror404.html', status=404)

#TODO Coding
def building_code(request):
    return render(request, 'task/coding.html')

#TODO Login
def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'เข้าสู่ระบบสำเร็จ')
            return redirect('taskcontrol:dashboard')
        else:
            messages.error(request, 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง')
    return render(request, 'accounts/login.html')

#TODO Logout
def logout_view(request):
    if request.user.is_authenticated:
        # last_login_time = request.user.last_login
        logout(request)
        messages.success(request, 'ออกจากระบบเรียบร้อย.')

        # if last_login_time is not None:
        #     current_time = datetime.now()
        #     time_difference = current_time - last_login_time

        #     if time_difference.total_seconds() > 3600:
        #         messages.success(request, 'ออกจากระบบ เนื่องจากไม่มีการใช้งานเกิน 1 ชั่วโมง.')
    return redirect('taskcontrol:login')

#TODO Others
def parse_date(date_string):
    if not date_string:
        return None
    try:
        return datetime.strptime(date_string, "%Y-%m-%d")
    except ValueError:
        print(f"Error parsing date string: {date_string}")
        return None

#TODO GetData
def get_districts(request):
    province_id = request.GET.get('province_id')
    district = District.objects.filter(province=province_id).all().values('id','name_th')
    return JsonResponse(list(district),safe=False)

def get_subdistricts(request):
    district_id = request.GET.get('district_id')
    subdistrict = Subdistrict.objects.filter(district=district_id).all().values('id', 'name_th', 'zipcode')
    return JsonResponse(list(subdistrict),safe=False)

def get_channel(request):
    channel_id = request.GET.get('channel_id')
    channel = Channel.objects.filter(id=channel_id).values('id', 'name')
    return JsonResponse(list(channel), safe=False)

def gen_engagement_code_auto(request):
    latest_job_code = Engagement.objects.aggregate(Max('job_code'))['job_code__max']

    # ตรวจสอบหาก latest_job_code เป็น None แล้วกำหนดให้เป็น '24-0001'
    if latest_job_code is not None:
        current_number = int(latest_job_code.split('-')[1]) + 1
    else:
        current_number = 1

    # ดึงปีปัจจุบัน
    current_year = datetime.now().year

    new_job_code = f'24-{current_number:04d}'

    return JsonResponse({'latest_job_code': new_job_code})

#TODO Client
@login_required
def client_list(request):
    clients_list = Client.objects.all().order_by('code')

    contacts = []
    for client in clients_list:
        first_contact = Contact.objects.filter(client_id=client.id).first()
        contacts.append(first_contact)

    return render(request, 'task/clients/client_list.html', {
        'clients_list': clients_list,
        'contacts': contacts,
    })

#TODO Record Client
@login_required
def record_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagement_all = Engagement.objects.filter(client_id=client_id).all()
    contact_all = Contact.objects.filter(client_id=client_id).all()
    return render(request, 'task/clients/record_client.html', {
        'client': client,
        'engagement_all':engagement_all,
        'contact_all':contact_all
    })

#TODO Client Detail
@login_required
def client_detail(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagements = Engagement.objects.filter(client_id=client_id).exclude(status='DONE').order_by('job_code')

    unique_engagements = []
    seen_job_codes = set()
    for engagement in engagements:
        if engagement.job_code not in seen_job_codes:
            unique_engagements.append(engagement)
            seen_job_codes.add(engagement.job_code)

    # Collect unique engagement types for each unique engagement
    engagement_data = []
    for engagement in unique_engagements:
        engagement_types = EngagementDetail.objects.filter(engagement=engagement).exclude(engagement__status='DONE').values_list('engagement_type__name_th', flat=True).distinct()
        engagement_data.append({
            'engagement': engagement,
            'types': list(set(engagement_types))  # Remove duplicates
        })

    contact_all = Contact.objects.filter(client_id=client_id)
    contacts = Contact.objects.all()
    subdistricts = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    districts = District.objects.values('id', 'name_th')
    provinces = Province.objects.all().order_by('name_th')
    register_types = RegisterType.objects.values('id', 'short_name', 'name_th', 'name_en')
    channels = Channel.objects.values('id', 'name')

    context = {
        'client': client,
        'engagement_data': engagement_data,
        'contact_all': contact_all,
        'contacts': contacts,
        'subdistricts': subdistricts,
        'districts': districts,
        'provinces': provinces,
        'register_types': register_types,
        'channels': channels,
    }
    return render(request, 'task/clients/client_detail.html', context)

#TODO Client Create
@login_required
def client_create(request):
    register_tax = None
    file = None
    contact = None
    client = None

    subdistrict = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    district = District.objects.values('id', 'name_th')
    province = Province.objects.values('id', 'name_th').order_by('name_th')
    register_types = RegisterType.objects.values('id','short_name','name_th','name_en')
    channels = Channel.objects.values('id','name')

    if request.method == 'POST':
        c_code = request.POST.get('c_code', '')
        c_company_name = request.POST.get('c_company_name', '')
        c_tax_id = request.POST.get('c_tax_id', '')
        c_address = request.POST.get('c_address')
        c_address2 = request.POST.get('c_address2')
        c_province = request.POST.get('c_province')
        c_district = request.POST.get('c_district')
        c_subdistrict = request.POST.get('c_subdistrict')
        c_channel = request.POST.get('c_channel')
        c_detail = request.POST.get('c_detail')
        c_status = request.POST.get('c_status')
        c_status = True if c_status == 'on' else False
        c_create_client_date = request.POST.get('c_create_client_date', '')

        r_company = request.POST.get('r_company') == 'True'
        r_company_date = request.POST.get('r_company_date')
        r_company_period_date = request.POST.get('r_company_period_date')
        r_vat = request.POST.get('r_vat') == 'True'
        r_vat_date = request.POST.get('r_vat_date')
        r_sbt = request.POST.get('r_sbt') == 'True'
        r_sbt_date = request.POST.get('r_sbt_date')
        r_sso = request.POST.get('r_sso') == 'True'
        r_sso_date = request.POST.get('r_sso_date')
        r_dbd_e_filling = request.POST.get('r_dbd_e_filling') == 'True'
        r_dbd_e_filling_date = request.POST.get('r_dbd_e_filling_date')
        
        date_c_create_client_date = parse_date(c_create_client_date)

        c_r_company_date = parse_date(r_company_date)
        c_r_company_period_date = parse_date(r_company_period_date)
        c_r_vat_date = parse_date(r_vat_date)
        c_r_sbt_date = parse_date(r_sbt_date)
        c_r_sso_date = parse_date(r_sso_date)
        c_r_dbd_e_filling_date = parse_date(r_dbd_e_filling_date)

        company_address = AddressBase(
            address = c_address,
            address2 = c_address2,
            province=Province.objects.filter(id=c_province).first(),
            district=District.objects.filter(id=c_district).first(),
            subdistrict=Subdistrict.objects.filter(id=c_subdistrict).first(),
        )
        company_address.save()

        client = Client(
            code=c_code,
            company_name=c_company_name,
            tax_id=c_tax_id,
            create_client_date = date_c_create_client_date,
            channel=Channel.objects.filter(id=c_channel).first(),
            detail=c_detail,
            status=c_status,
            register_tax=register_tax,
            company_address = company_address,
            create_by=request.user,
        )
        client.save()

        register_tax = RegisterTax(
            vat=r_vat,
            vat_date=c_r_vat_date,
            sbt=r_sbt,
            sbt_date=c_r_sbt_date,
            sso=r_sso,
            sso_date=c_r_sso_date,
            dbd_e_filling=r_dbd_e_filling,
            dbd_e_filling_date=c_r_dbd_e_filling_date,

taskcontrol/templates/task/engagement/engagement_file.html
{% extends 'task/index.html' %} {% block content %}
<style>
    .card {
        margin-top: 1rem;
    }

    .card, .card-body {
        box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 2px 0px;
        background-color: #eaf4ff;
        border-radius: 20px;
    }

    .text-center {
        text-align: center;
    }

    .mx-auto {
        margin-left: auto;
        margin-right: auto;
    }

    .pl-0 {
        padding-left: 0;
    }

    .mt-3 {
        margin-top: 2rem;
    }

    .d-none {
        display: none;
    }

    .form-step {
        box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 2px 0px;
        border-radius: 20px;
        margin-top: 1rem;
        padding: 2rem;
        background-color: #fff;
    }

    ul.form-stepper {
        counter-reset: section;
        margin-bottom: 1.5rem;
    }

    ul.form-stepper .form-stepper-circle {
        position: relative;
    }

    ul.form-stepper .form-stepper-circle span {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translateY(-50%) translateX(-50%);
    }

    .form-stepper-horizontal {
        position: relative;
        display: flex;
        justify-content: space-around;
    }

    ul.form-stepper>li:not(:last-of-type) {
        margin-bottom: 0.625rem;
        transition: margin-bottom 0.4s;
    }

    .form-stepper-horizontal>li:not(:last-of-type) {
        margin-bottom: 0 !important;
    }

    .form-stepper-horizontal li {
        position: relative;
        display: flex;
        flex: 1;
        align-items: baseline;
        flex-wrap: nowrap;
        transition: 0.5s;
    }

    .form-stepper-horizontal li:not(:last-child):after {
        position: relative;
        flex: 1;
        height: 1px;
        content: "";
        top: 32%;
    }

    .form-stepper-horizontal li:after {
        background-color: #5d87ff;
    }

    .form-stepper-horizontal li.form-stepper-completed:after {
        background-color: #0277ff;
    }

    .form-stepper-horizontal li:last-child {
        flex: unset;
    }

    ul.form-stepper li a .form-stepper-circle {
        display: inline-block;
        margin-right: 0;
        line-height: 1.7rem;
        text-align: center;
        background: rgba(0, 0, 0, 0.38);
        border-radius: 50%;
    }

    .form-stepper .form-stepper-active .form-stepper-circle {
        background-color: #0277ff !important;
    }

    .form-stepper .form-stepper-active .label {
        color: #0277ff !important;
    }

    .form-stepper .form-stepper-active .form-stepper-circle:hover {
        background-color: #0277ff !important;
    }

    .form-stepper .form-stepper-unfinished .form-stepper-circle {
        background-color: #f5f5f5;

    }

    .form-stepper .form-stepper-completed .form-stepper-circle {
        background-color: #0277ff !important;
    }

    .form-stepper .form-stepper-completed .label {
        color: #0277ff !important;
    }

    .form-stepper .form-stepper-completed .form-stepper-circle:hover {
        background-color: #0277ff !important;
    }

    .form-stepper .label {
        font-size: 14.5px;
        font-weight: 500;
        margin-top: 0.5rem;
    }

    .form-stepper a {
        cursor: default;
    }

    .number-lable {
        color: #333944;
        font-size: 12.5px;
        font-weight: 600;
    }

    .number-step {
        color: #205aff;
        font-weight: 700;
        font-size: 18px;
    }

    .text-muted {
        --bs-text-opacity: 1;
        color: #205aff !important;
    }

    .form-check-input:checked {
        font-size: 16px;
    }

    th {
        font-size: 13px;
    }

    td {
        font-size: 13.5px;
    }

    .file-name {
        font-size: 12px;
    }

</style>

<div class="card">
    <div class="card-body">
        <ul class="form-stepper form-stepper-horizontal text-center mx-auto pl-0 ">
            <!-- Step 1 -->
            <li class="form-stepper-unfinished text-center form-stepper-list">
                <a class="mx-2">
                    <span class="number-step"><i class="fi fi-sr-add-document"></i></span>
                    <div class="number-lable">Engagement</div>
                    <span class="form-stepper-circle text-muted">
                        <span><i class="fa-solid fa-circle-check fa-lg"></i></span>
                    </span>
                </a>
            </li>
            <!-- Step 2 -->
            <li class="form-stepper-unfinished text-center form-stepper-list">
                <a class="mx-2">
                    <span class="number-step"><i class="fi fi-sr-document"></i></span>
                    <div class="number-lable">รายละเอียดงาน</div>
                    <span class="form-stepper-circle text-muted">
                        <span><i class="fa-solid fa-circle-check fa-lg"></i></span>
                    </span>
                </a>
            </li>
            <!-- Step 3 -->
            <li class="form-stepper-unfinished text-center form-stepper-list">
                <a class="mx-2">
                    <span class="number-step"><i class="fi fi-br-clip"></i></span>
                    <div class="number-lable">เอกสารเพิ่มเติม</div>
                    <span class="form-stepper-circle text-muted">
                        <span><i class="fa-regular fa-circle-dot fa-lg"></i></span>
                    </span>
                </a>
            </li>
        </ul>

        <section class="form-step mb-3">
            <div class="mt-1">
                <form method="post" enctype="multipart/form-data" action="{% url 'taskcontrol:file_engagement_create' engagement_id=engagement.id %}">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <label for="engagement_description" class="form-label">คำอธิบาย :</label>
                            <input type="text" name="engagement_description" class="form-control" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="engagement_file" class="form-label me-2">ไฟล์ <span style="font-size: 0.75rem; color: tomato;"> .pdf, .doc, etc.,</span> :</label>
                            <input type="file" name="engagement_file" class="form-control" accept=".pdf, .doc, .docx, .txt">
                        </div>
                        <div class="col-md-6">
                            <label for="engagement_image" class="form-label">รูปภาพ <span style="font-size: 0.75rem; color: tomato;">.png, .jpg etc.,</span> :</label>
                            <input type="file" name="engagement_image" class="form-control" accept="image/*">
                        </div>
                    </div>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-3">
                        <button type="submit" class="btn btn-primary">อัปโหลด <i class="fi fi-br-upload"></i></button>
                    </div>
                </form>
    
                <div class="table-responsive mb-4">
                    <table id="file-engagement-table" class="table table-bordered">
                        <thead class="table-light">
                            <tr>
                                <th style="width: 5%;">#</th>
                                <th style="width: 10%;">คำอธิบาย</th>
                                <th style="width: 40%;">ไฟล์</th>
                                <th style="width: 40%;">รูปภาพ</th>
                                <th class="text-center" style="width: 5%;"><i class="fa-solid fa-gears"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for file in engagement_files %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ file.description }}</td>
                                    <td>
                                        {% if file.file_engagement %}
                                        <a href="{% url 'taskcontrol:download_file_engagement' file_id=file.id %}" class="btn btn-outline-primary btn-sm me-2" download target="_blank">
                                            <i class="fi fi-br-download"></i>
                                        </a>
                                        {% endif %}
                                        <span class="file-name">{{ file.file_engagement }}</span>
                                    </td>
                                    <td>
                                        {% if file.image_engagement %}
                                            <a href="{% url 'taskcontrol:download_image_engagement' image_id=file.id %}" class="btn btn-outline-primary btn-sm me-2" download target="_blank">
                                                <i class="fi fi-br-download"></i>
                                            </a>
                                        {% endif %}
                                        <span class="file-name">{{ file.image_engagement }}</span>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-outline-danger btn-sm delete-btn" data-file-id="{{ file.id }}"
                                            data-delete-url="{% url 'taskcontrol:file_engagement_delete' file_id=file.id %}">
                                            <i class="fa-solid fa-trash-can"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a href="{% url 'taskcontrol:engagement_job_create' engagement_id=engagement.id %}" class="btn btn-outline-dark"><i class="fa-solid fa-circle-arrow-left"></i> ย้อนกลับ</a>
                <a href="{% url 'taskcontrol:engagement_detail' engagement_id=engagement.id %}" class="btn btn-dark">ถัดไป <i class="fa-solid fa-circle-arrow-right"></i></a>
            </div>
        </section>
    </div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
document.addEventListener("DOMContentLoaded", function() {
    const deleteButtons = document.querySelectorAll(".delete-btn");
    deleteButtons.forEach(button => {
        button.addEventListener("click", function() {
            handleDelete(this);
        });
    });

    function handleDelete(button) {
        const fileId = button.getAttribute("data-file-id");
        const confirmation = confirm("ต้องการลบประเภทงานนี้ ?");
        if (confirmation) {
            const deleteUrl = button.getAttribute("data-delete-url");
            fetch(deleteUrl, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': getCsrfToken(),
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ file_id: fileId })
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(data => {
                if (data.success) {
                    location.reload();
                } else {
                    alert('Error deleting item. Please try again.');
                }
            })
            .catch(error => {
                console.error('There was a problem with the fetch operation:', error);
                alert('Error deleting item. Please try again.');
            });
        }
    }

    function getCsrfToken() {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, 'csrftoken'.length + 1) === ('csrftoken=')) {
                    cookieValue = decodeURIComponent(cookie.substring('csrftoken'.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
});
</script>
<script>
    $(document).ready(function () {
         const dataTable = $("#file-engagement-table").DataTable({
              "language": {
                   "search": "ค้นหา",
                   "lengthMenu": "แสดง _MENU_ รายการ",
                   "info": "แสดง _START_ ถึง _END_ จากทั้งหมด _TOTAL_ รายการ",
                   "paginate": {
                        "previous": "ก่อนหน้า",
                        "next": "ถัดไป"
                   }
              }
         });
    });
</script>

{% endblock content %}