pconnectacc/urls.py
from django.contrib import admin
from django.urls import path, include
from taskcontrol import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task-control/', include('taskcontrol.urls')),
]

taskcontrol/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = "taskcontrol"

handler404 = 'taskcontrol.views.error_404_view'

urlpatterns = [
    path('eror404/', error_404_view, name='eror404'),
    path('coding/', building_code, name='building_code'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    # path('test/', testpage, name='testpage'),
    path('get_districts/', get_districts, name='GetDistrict'),
    path('get_subdistricts/', get_subdistricts, name='GetSubdistrict'),
    path('gen_engagement_code_auto/', gen_engagement_code_auto, name='get_latest_job_code'),
    path('get_channel/', get_channel, name='get_channel'),

    path('get_engagement_type/', get_engagement_type, name='get_engagement_type'),
    path('api/get_engagement_details/', get_engagement_details, name='get_engagement_details'),



    path('client/list/', client_list, name='client_list'),
    path('client/<int:client_id>/', record_client, name='record_client'),

    path('client/create/', client_create, name='client_create'),
    path('client/detail/<int:client_id>/', client_detail, name='client_detail'),
    path('client/update/<int:client_id>/', client_update, name='client_update'),
    path('client/delete/<int:client_id>/', client_delete, name='client_delete'),

    path('client/contact_create/<int:client_id>/', create_contact, name='create_contact'),
    path('client/contact_delete/<int:contact_id>/', delete_contact, name='delete_contact'),

    path('client/password/<int:client_id>/', password_list, name='password_list'),
    path('client/password_create/<int:client_id>/', create_password, name='create_password'),
    path('client/password_update/<int:password_id>/', update_password, name='update_password'),
    path('client/password_delete/<int:password_id>/', delete_password, name='delete_password'),

    path('client/file_list/<int:client_id>/', file_client_list, name='file_client_list'),
    path('client/file_create/<int:client_id>/', file_client_create, name='file_client_create'),
    path('client/file_delete/<int:file_id>/', file_client_delete, name='file_client_delete'),
    path('client/file_client_download_file/<int:file_id>/', file_client_download_file, name='file_client_download_file'),
    path('client/file_client_download_image/<int:image_id>/', file_client_download_image, name='file_client_download_image'),

    path('engagement/list/', engagement_list, name='engagement_list'),
    path('engagement/create/', engagement_create, name='engagement_create'),
    path('engagement/<int:engagement_id>/', record_engagement, name='record_engagement'),
    path('engagement/detail/<int:engagement_id>/', engagement_detail, name='engagement_detail'),
    path('engagement/update/<int:engagement_id>/', engagement_update, name='engagement_update'),
    path('engagement/delete/<int:engagement_id>/', engagement_delete, name='engagement_delete'),

    path('engagement/detail_job/<int:engagement_id>/', engagement_job, name='engagement_job'),
    path('engagement/detail_job/create/<int:engagement_id>/', engagement_job_create, name='engagement_job_create'),
    path('engagement/detail_job/delete/<int:engagement_job_id>/', engagement_job_delete, name='engagement_job_delete'),

    path('engagement/file_list/<int:engagement_id>/', file_engagement_list, name='file_engagement_list'),
    path('engagement/file_create/<int:engagement_id>/', file_engagement_create, name='file_engagement_create'),
    path('engagement/file_delete/<int:file_id>/', file_engagement_delete, name='file_engagement_delete'),
    path('engagement/file_client_download_file/<int:file_id>/', download_file_engagement, name='download_file_engagement'),
    path('engagement/file_client_download_image/<int:image_id>/', download_image_engagement, name='download_image_engagement'),

    path('manage_category/', manage_category, name='manage_category'),
    path('manage_category/update/<int:category_id>/', update_category, name='update_category'),
    path('manage_category/delete/<int:category_id>/', delete_category, name='delete_category'),

    path('manage_type/', manage_type, name='manage_type'),
    path('manage_type/update/<int:type_id>/', update_type, name='update_type'),
    path('manage_type/delete/<int:type_id>/', delete_type, name='delete_type'),

    path('manage_channel/', manage_channel, name='manage_channel'),
    path('manage_channel/update/<int:channel_id>/', update_channel, name='update_channel'),
    path('manage_channel/delete/<int:channel_id>/', delete_channel, name='delete_channel'),

    path('manage_register_type/', manage_register_type, name='manage_register_type'),
    path('manage_register_type/update/<int:register_type_id>/', update_register_type, name='update_register_type'),
    path('manage_register_type/delete/<int:register_type_id>/', delete_register_type, name='delete_register_type'),

    path('kanban_board/', kanban_board, name='kanban_board'),
    path('update_engagement_detail_status', update_engagement_detail_status, name='update_engagement_detail_status'),
    path('update_task_status', update_task_status, name='update_task_status'),
    path('add_new_task/', add_new_task, name='add_new_task'),

    path('kanban_board_filter/', kanban_board_filter, name='kanban_board_filter'),
    path('get_status_counts/', get_status_counts, name='get_status_counts'),
    path('update_near_deadline/', update_near_deadline, name='update_near_deadline'),
    path('get_date_deadlines/', get_date_deadlines, name='get_date_deadlines'),

    
    path('update_engagement_detail_comment', update_engagement_detail_comment, name='update_engagement_detail_comment'),
    path('search_filter_engagement_details/', search_filter_engagement_details, name='search_filter_engagement_details'),
    path('get_filter_engagement_details/', get_filter_engagement_details, name='get_filter_engagement_details'),

    path('dashboard/', dashboard, name='dashboard'),
    path('api/engagement-details/', get_engagement_detail_dashboard, name='get_engagement_detail_dashboard'),
    # path('search_datatable/', search_datatable, name='search_datatable'),
    path('get_engagement_detail_status/', get_engagement_detail_status, name='get_engagement_detail_status'),
    path('get_accounting/', get_accounting, name='get_accounting'),
    path('get_tax/', get_tax, name='get_tax'),
    path('get_payroll/', get_payroll, name='get_payroll'),
    path('get_report/', get_report, name='get_report'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskcontrol/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.db import models
from taskcontrol.models import FileManage

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254)

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

taskcontrol/views.py
from django.shortcuts import render, redirect, get_object_or_404
from taskcontrol.models import *
from .forms import CustomUserCreationForm, CustomPasswordResetForm
from datetime import datetime, date, timedelta
from django.utils import timezone
from django.contrib import messages
from django.db import transaction
from django.utils.dateparse import parse_date
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseBadRequest, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.db.models import Max, Count, F, Subquery, Q, Case, When, Value, CharField, Prefetch
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from collections import Counter
from django.views.decorators.http import require_POST
from dateutil.relativedelta import relativedelta
from django.views.decorators.csrf import csrf_exempt
from django.db.models.functions import ExtractMonth, ExtractYear
import json


# Constants
STATUS_OPEN_JOB = ('OPEN_JOB', 'PENDING_CLIENT', 'REVIEW', 'IN_PROGRESS')
STATUS_DONE = ('DONE',)

#TODO Error404
def error_404_view(request, exception):
    return render(request, 'task/eror404.html', status=404)

#TODO Coding
def building_code(request):
    return render(request, 'task/coding.html')

#TODO Login
def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'เข้าสู่ระบบสำเร็จ')
            return redirect('taskcontrol:dashboard')
        else:
            messages.error(request, 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง')
    return render(request, 'accounts/login.html')

#TODO Logout
def logout_view(request):
    if request.user.is_authenticated:
        # last_login_time = request.user.last_login
        logout(request)
        messages.success(request, 'ออกจากระบบเรียบร้อย.')

        # if last_login_time is not None:
        #     current_time = datetime.now()
        #     time_difference = current_time - last_login_time

        #     if time_difference.total_seconds() > 3600:
        #         messages.success(request, 'ออกจากระบบ เนื่องจากไม่มีการใช้งานเกิน 1 ชั่วโมง.')
    return redirect('taskcontrol:login')

#TODO Others
def parse_date(date_string):
    if not date_string:
        return None
    try:
        return datetime.strptime(date_string, "%Y-%m-%d")
    except ValueError:
        print(f"Error parsing date string: {date_string}")
        return None

#TODO GetData
def get_districts(request):
    province_id = request.GET.get('province_id')
    district = District.objects.filter(province=province_id).all().values('id','name_th')
    return JsonResponse(list(district),safe=False)

def get_subdistricts(request):
    district_id = request.GET.get('district_id')
    subdistrict = Subdistrict.objects.filter(district=district_id).all().values('id', 'name_th', 'zipcode')
    return JsonResponse(list(subdistrict),safe=False)

def get_channel(request):
    channel_id = request.GET.get('channel_id')
    channel = Channel.objects.filter(id=channel_id).values('id', 'name')
    return JsonResponse(list(channel), safe=False)

def gen_engagement_code_auto(request):
    latest_job_code = Engagement.objects.aggregate(Max('job_code'))['job_code__max']

    # ตรวจสอบหาก latest_job_code เป็น None แล้วกำหนดให้เป็น '24-0001'
    if latest_job_code is not None:
        current_number = int(latest_job_code.split('-')[1]) + 1
    else:
        current_number = 1

    # ดึงปีปัจจุบัน
    current_year = datetime.now().year

    new_job_code = f'24-{current_number:04d}'

    return JsonResponse({'latest_job_code': new_job_code})

#TODO Client
@login_required
def client_list(request):
    clients_list = Client.objects.all().order_by('code')

    contacts = []
    for client in clients_list:
        first_contact = Contact.objects.filter(client_id=client.id).first()
        contacts.append(first_contact)

    return render(request, 'task/clients/client_list.html', {
        'clients_list': clients_list,
        'contacts': contacts,
    })

#TODO Record Client
@login_required
def record_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagement_all = Engagement.objects.filter(client_id=client_id).all()
    contact_all = Contact.objects.filter(client_id=client_id).all()
    return render(request, 'task/clients/record_client.html', {
        'client': client,
        'engagement_all':engagement_all,
        'contact_all':contact_all
    })

#TODO Client Detail
@login_required
def client_detail(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagements = Engagement.objects.filter(client_id=client_id).exclude(status='DONE').order_by('job_code')

    unique_engagements = []
    seen_job_codes = set()
    for engagement in engagements:
        if engagement.job_code not in seen_job_codes:
            unique_engagements.append(engagement)
            seen_job_codes.add(engagement.job_code)

    # Collect unique engagement types for each unique engagement
    engagement_data = []
    for engagement in unique_engagements:
        engagement_types = EngagementDetail.objects.filter(engagement=engagement).exclude(engagement__status='DONE').values_list('engagement_type__name_th', flat=True).distinct()
        engagement_data.append({
            'engagement': engagement,
            'types': list(set(engagement_types))  # Remove duplicates
        })

    contact_all = Contact.objects.filter(client_id=client_id)
    contacts = Contact.objects.all()
    subdistricts = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    districts = District.objects.values('id', 'name_th')
    provinces = Province.objects.all().order_by('name_th')
    register_types = RegisterType.objects.values('id', 'short_name', 'name_th', 'name_en')
    channels = Channel.objects.values('id', 'name')

    context = {
        'client': client,
        'engagement_data': engagement_data,
        'contact_all': contact_all,
        'contacts': contacts,
        'subdistricts': subdistricts,
        'districts': districts,
        'provinces': provinces,
        'register_types': register_types,
        'channels': channels,
    }
    return render(request, 'task/clients/client_detail.html', context)

#TODO Client Create
@login_required
def client_create(request):
    register_tax = None
    file = None
    contact = None
    client = None

    subdistrict = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    district = District.objects.values('id', 'name_th')
    province = Province.objects.values('id', 'name_th').order_by('name_th')
    register_types = RegisterType.objects.values('id','short_name','name_th','name_en')
    channels = Channel.objects.values('id','name')

    if request.method == 'POST':
        c_code = request.POST.get('c_code', '')
        c_company_name = request.POST.get('c_company_name', '')
        c_tax_id = request.POST.get('c_tax_id', '')
        c_address = request.POST.get('c_address')
        c_address2 = request.POST.get('c_address2')
        c_province = request.POST.get('c_province')
        c_district = request.POST.get('c_district')
        c_subdistrict = request.POST.get('c_subdistrict')
        c_channel = request.POST.get('c_channel')
        c_detail = request.POST.get('c_detail')
        c_status = request.POST.get('c_status')
        c_status = True if c_status == 'on' else False
        c_create_client_date = request.POST.get('c_create_client_date', '')

        r_company = request.POST.get('r_company') == 'True'
        r_company_date = request.POST.get('r_company_date')
        r_company_period_date = request.POST.get('r_company_period_date')
        r_vat = request.POST.get('r_vat') == 'True'
        r_vat_date = request.POST.get('r_vat_date')
        r_sbt = request.POST.get('r_sbt') == 'True'
        r_sbt_date = request.POST.get('r_sbt_date')
        r_sso = request.POST.get('r_sso') == 'True'
        r_sso_date = request.POST.get('r_sso_date')
        r_dbd_e_filling = request.POST.get('r_dbd_e_filling') == 'True'
        r_dbd_e_filling_date = request.POST.get('r_dbd_e_filling_date')
        
        date_c_create_client_date = parse_date(c_create_client_date)

        c_r_company_date = parse_date(r_company_date)
        c_r_company_period_date = parse_date(r_company_period_date)
        c_r_vat_date = parse_date(r_vat_date)
        c_r_sbt_date = parse_date(r_sbt_date)
        c_r_sso_date = parse_date(r_sso_date)
        c_r_dbd_e_filling_date = parse_date(r_dbd_e_filling_date)

        company_address = AddressBase(
            address = c_address,
            address2 = c_address2,
            province=Province.objects.filter(id=c_province).first(),
            district=District.objects.filter(id=c_district).first(),
            subdistrict=Subdistrict.objects.filter(id=c_subdistrict).first(),
        )
        company_address.save()

        client = Client(
            code=c_code,
            company_name=c_company_name,
            tax_id=c_tax_id,
            create_client_date = date_c_create_client_date,
            channel=Channel.objects.filter(id=c_channel).first(),
            detail=c_detail,
            status=c_status,
            register_tax=register_tax,
            company_address = company_address,
            create_by=request.user,
        )
        client.save()

        register_tax = RegisterTax(
            vat=r_vat,
            vat_date=c_r_vat_date,
            sbt=r_sbt,
            sbt_date=c_r_sbt_date,
            sso=r_sso,
            sso_date=c_r_sso_date,
            dbd_e_filling=r_dbd_e_filling,
            dbd_e_filling_date=c_r_dbd_e_filling_date,

taskcontrol/templates/task/tasks/cards.html
{% extends 'tasks/templates.html' %}
{% block content %}

{% endblock content %}

taskcontrol/templates/task/tasks/forms.html
{% load static %}

<html lang="en">

<head>
    <title>Test</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
</head>

<body>
    <div class="col-sm-4">
        <div class="form-group">
            <select name="province" id="province" class="form-select form-select-sm">
                <option value selected disabled hidden>จังหวัด</option>
                {% for p in province %}
                <option value="{{ p.id }}">{{ p.name_th }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <select name="district" id="district" class="form-select form-select-sm">
                <option value="" selected disabled hidden>อำเภอ</option>
            </select>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <select name="subdistrict" id="subdistrict" class="form-select form-select-sm">
                <option value="" selected disabled hidden>ตำบล</option>
            </select>
        </div>
    </div>
    
    <script type="text/javascript">
        $(function() {
            $('#province').change(function() {
                $("#district").empty()
                $.ajax({
                    url: '{% url 'taskcontrol:GetDistrict' %}',
                    data: {province_id: $(this).val()
                    },
                    success: function(data) {
                        $("#district").append('<option value selected disabled hidden>อำเภอ</option>')
                        $.each(data, function(index, value) {
                            $("#district").append('<option value="' + data[index].id + '">' + data[index].name_th + '</option>')
                        })
                    }
                })
            })
            $('#district').change(function() {
                $('#subdistrict').empty()
                $.ajax({
                    url : '{% url 'taskcontrol:GetSubdistrict' %}',
                    data: {district_id: $(this).val()},
                    success: function(data) {
                        $('#subdistrict').append('<option value selected disabled hidden>ตำบล</option>')
                        $.each(data, function(i, v) {
                            $('#subdistrict').append('<option value="' + data[i].id + '">' + data[i].name_th + '  ' + data[i].zipcode + '</option>');
                        })
                    }
                })
            })
        });
    </script>
</body>

</html>

taskcontrol/templates/task/tasks/task.html
{% extends 'tasks/base.html' %}
{% block content %}

<div class="card card-side shadow-xl  bg-white">
  <div class="card-body">
    <h1>ติดตามงาน</h1>

    <!--Tab-->
    <div class="join">
      <button class="btn join-item">เดดไลน์</button>
      <button class="btn join-item">คนดูแล</button>
      <button class="btn join-item">ประเภทงาน</button>
      <button class="btn join-item">Period</button>
    </div>

    <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
    <div class="relative">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
          fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
        </svg>
      </div>
      <input type="search" id="default-search"
        class="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
        placeholder="Search Mockups, Logos..." required>
      <button type="submit"
        class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
    </div>

    <!--Tasks Borad-->
    <div class="grid grid-flow-col auto-cols-max">
      <div class="board  bg-white bg-opacity-80" id="board1">
        <header>เปิดงาน</header>
        <div class="cards" id="b1">
          <div class="card"><span class="cardtitle noselect">A great card #1</span></div>
          <div class="card"><span class="cardtitle noselect">A great card #2</span></div>
          <div class="card"><span class="cardtitle noselect">A great card #3</span></div>
          <div class="card"><span class="cardtitle noselect">A great card #4</span></div>
        </div>
      </div>

      <div class="board" id="board2">
        <header>กำลังดำเนินงาน</header>
        <div class="cards" id="b2">
          <div class="card"><span class="cardtitle">A great card #5</span></div>
        </div>
      </div>

      <div class="board" id="board3">
        <header>รอตรวจทาน</header>
        <div class="cards" id="b3">
          <div class="card"><span class="cardtitle noselect">A great card #6</span></div>
        </div>
      </div>

      <div class="board" id="board4">
        <header>รอลูกค้า</header>
        <div class="cards" id="b4">
          <div class="card"><span class="cardtitle noselect">A great card #7</span></div>
        </div>
      </div>

      <div class="board" id="board5">
        <header>เรียบร้อย</header>
        <div class="cards" id="b5">
          <div class="card"><span class="cardtitle noselect">A great card #8</span></div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock content %}

taskcontrol/templates/task/tasks/taskscontrol copy.html
{% extends 'tasks/base.html' %}
{% block content %}
    <div class="card card-side bg-base-100 shadow-xl m-7">
        <div class="card-body">
            <div>
                <div class="join">
                    <button class="btn join-item">เดดไลน์</button>
                    <button class="btn join-item">คนดูแล</button>
                    <button class="btn join-item">ประเภทงาน</button>
                    <button class="btn join-item">Period</button>

                    <div>
                        <div>
                        <input class="input input-bordered join-item" placeholder="Search"/>
                        </div>
                    </div>
                    <select class="select select-bordered join-item">
                        <option disabled selected>Filter</option>
                        <option>Sci-fi</option>
                        <option>Drama</option>
                        <option>Action</option>
                    </select>
                    <div>
                        <button class="btn join-item">Search</button>
                    </div>
                </div>

                <!--table-->
                <div class="grid gap-6 mb-6 md:grid-cols-5">
                    <div>
                    </div>
                </div>
            </div> 
        </div>
    </div>
{% endblock content %}

taskcontrol/templates/task/tasks/templates.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'src/tailwind.output.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>

    <link href="https://cdn.jsdelivr.net/npm/daisyui@3.9.2/dist/full.css" rel="stylesheet" type="text/css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.min.js"></script>
    <script src="{% static 'js/init-alpine.js' %}"></script>
</head>
<style>
    html {
        font-size: 62.5%;
        font-family: serif;
    }
    body {
        font-size: 1.8rem;
        line-height: 1.618;
        max-width: 38em;
        margin: auto;
        color: #4a4a4a;
        background-color: #f9f9f9;
        padding: 13px;
    }
    @media (max-width: 684px) 
    {
        body {
            font-size: 1.53rem;
        }
        }@media (max-width: 382px) {
        body {
            font-size: 1.35rem;
        }
    }
    h1, h2, h3, h4, h5, h6 {
        line-height: 1.1;
        font-family: Verdana, Geneva, sans-serif;
        font-weight: 700;
        overflow-wrap: break-word;
        word-wrap: break-word;
        -ms-word-break: break-all;
        word-break: break-word;
        -ms-hyphens: auto;
        -moz-hyphens: auto;
        -webkit-hyphens: auto;
        hyphens: auto;
    }
    h1 {
        font-size: 2.35em;
    }
    h2 {
        font-size: 2em;
    }
    h3 {
        font-size: 1.75em;
    }
    h4 {
        ont-size: 1.5em;
    }
    h5 {
        font-size: 1.25em;
    }
    h6 {
        font-size: 1em;
    }

    header, footer {
        font-size: large;
        text-align: center;
        padding: 0.3em 0;
        background-color: #4a4a4a;
        color: #f9f9f9;
    }
    nav {
        background: #eee;
    }
    main {
        background: #f9f9f9;
    }
    aside {
        background: #eee;
    }
</style>

<body>
    <header>นี่คือส่วนหัว</header>
    <main>
        <h1>นี่คือเนื้อหาหลัก</h1>
        <p>...</p>
    </main>
    <nav>
        <h4>นี่คือส่วนการนำทาง</h4>
        <p>...</p>
    </nav>
    <div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen}">
        <aside class="z-20 hidden w-64 overflow-y-auto bg-white dark:bg-gray-800 md:block flex-shrink-0">
            <h4>นี่คือส่วนอื่น ๆ</h4>
            <a href="{% url 'taskcontrol:dashboard' %}"><i class="fa fa-user-o" aria-hidden="true"></i>dashboard</a>
            <a href="{% url 'taskcontrol:Forms' %}"><i class="fa fa-laptop" aria-hidden="true"></i>Forms</a>
            <a href="{% url 'taskcontrol:Cards' %}"><i class="fa fa-clone" aria-hidden="true"></i>Cards</a>
            <a href="{% url 'taskcontrol:Charts' %}"><i class="fa fa-star-o" aria-hidden="true"></i>Charts</a>
            <a href="{% url 'taskcontrol:Tables' %}"><i class="fa fa-trash-o" aria-hidden="true"></i>Tables</a>
        </aside>
    </div>

    {% block content %}
    {% endblock %}
    <footer>นี่คือส่วนท้าย</footer>
</body>

</html>