pconnectacc/urls.py
from django.contrib import admin
from django.urls import path, include
from taskcontrol import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task-control/', include('taskcontrol.urls')),
]

taskcontrol/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = "taskcontrol"

handler404 = 'taskcontrol.views.error_404_view'

urlpatterns = [
    path('eror404/', error_404_view, name='eror404'),
    path('coding/', building_code, name='building_code'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    # path('test/', testpage, name='testpage'),
    path('get_districts/', get_districts, name='GetDistrict'),
    path('get_subdistricts/', get_subdistricts, name='GetSubdistrict'),
    path('gen_engagement_code_auto/', gen_engagement_code_auto, name='get_latest_job_code'),
    path('get_channel/', get_channel, name='get_channel'),

    path('get_engagement_type/', get_engagement_type, name='get_engagement_type'),
    path('api/get_engagement_details/', get_engagement_details, name='get_engagement_details'),



    path('client/list/', client_list, name='client_list'),
    path('client/<int:client_id>/', record_client, name='record_client'),

    path('client/create/', client_create, name='client_create'),
    path('client/detail/<int:client_id>/', client_detail, name='client_detail'),
    path('client/update/<int:client_id>/', client_update, name='client_update'),
    path('client/delete/<int:client_id>/', client_delete, name='client_delete'),

    path('client/contact_create/<int:client_id>/', create_contact, name='create_contact'),
    path('client/contact_delete/<int:contact_id>/', delete_contact, name='delete_contact'),

    path('client/password/<int:client_id>/', password_list, name='password_list'),
    path('client/password_create/<int:client_id>/', create_password, name='create_password'),
    path('client/password_update/<int:password_id>/', update_password, name='update_password'),
    path('client/password_delete/<int:password_id>/', delete_password, name='delete_password'),

    path('client/file_list/<int:client_id>/', file_client_list, name='file_client_list'),
    path('client/file_create/<int:client_id>/', file_client_create, name='file_client_create'),
    path('client/file_delete/<int:file_id>/', file_client_delete, name='file_client_delete'),
    path('client/file_client_download_file/<int:file_id>/', file_client_download_file, name='file_client_download_file'),
    path('client/file_client_download_image/<int:image_id>/', file_client_download_image, name='file_client_download_image'),

    path('engagement/list/', engagement_list, name='engagement_list'),
    path('engagement/create/', engagement_create, name='engagement_create'),
    path('engagement/<int:engagement_id>/', record_engagement, name='record_engagement'),
    path('engagement/detail/<int:engagement_id>/', engagement_detail, name='engagement_detail'),
    path('engagement/update/<int:engagement_id>/', engagement_update, name='engagement_update'),
    path('engagement/delete/<int:engagement_id>/', engagement_delete, name='engagement_delete'),

    path('engagement/detail_job/<int:engagement_id>/', engagement_job, name='engagement_job'),
    path('engagement/detail_job/create/<int:engagement_id>/', engagement_job_create, name='engagement_job_create'),
    path('engagement/detail_job/delete/<int:engagement_job_id>/', engagement_job_delete, name='engagement_job_delete'),

    path('engagement/file_list/<int:engagement_id>/', file_engagement_list, name='file_engagement_list'),
    path('engagement/file_create/<int:engagement_id>/', file_engagement_create, name='file_engagement_create'),
    path('engagement/file_delete/<int:file_id>/', file_engagement_delete, name='file_engagement_delete'),
    path('engagement/file_client_download_file/<int:file_id>/', download_file_engagement, name='download_file_engagement'),
    path('engagement/file_client_download_image/<int:image_id>/', download_image_engagement, name='download_image_engagement'),

    path('manage_category/', manage_category, name='manage_category'),
    path('manage_category/update/<int:category_id>/', update_category, name='update_category'),
    path('manage_category/delete/<int:category_id>/', delete_category, name='delete_category'),

    path('manage_type/', manage_type, name='manage_type'),
    path('manage_type/update/<int:type_id>/', update_type, name='update_type'),
    path('manage_type/delete/<int:type_id>/', delete_type, name='delete_type'),

    path('manage_channel/', manage_channel, name='manage_channel'),
    path('manage_channel/update/<int:channel_id>/', update_channel, name='update_channel'),
    path('manage_channel/delete/<int:channel_id>/', delete_channel, name='delete_channel'),

    path('manage_register_type/', manage_register_type, name='manage_register_type'),
    path('manage_register_type/update/<int:register_type_id>/', update_register_type, name='update_register_type'),
    path('manage_register_type/delete/<int:register_type_id>/', delete_register_type, name='delete_register_type'),

    path('kanban_board/', kanban_board, name='kanban_board'),
    path('update_engagement_detail_status', update_engagement_detail_status, name='update_engagement_detail_status'),
    path('update_task_status', update_task_status, name='update_task_status'),
    path('add_new_task/', add_new_task, name='add_new_task'),

    path('kanban_board_filter/', kanban_board_filter, name='kanban_board_filter'),
    path('get_status_counts/', get_status_counts, name='get_status_counts'),
    path('update_near_deadline/', update_near_deadline, name='update_near_deadline'),
    path('get_date_deadlines/', get_date_deadlines, name='get_date_deadlines'),

    
    path('update_engagement_detail_comment', update_engagement_detail_comment, name='update_engagement_detail_comment'),
    path('search_filter_engagement_details/', search_filter_engagement_details, name='search_filter_engagement_details'),
    path('get_filter_engagement_details/', get_filter_engagement_details, name='get_filter_engagement_details'),

    path('dashboard/', dashboard, name='dashboard'),
    path('api/engagement-details/', get_engagement_detail_dashboard, name='get_engagement_detail_dashboard'),
    # path('search_datatable/', search_datatable, name='search_datatable'),
    path('get_engagement_detail_status/', get_engagement_detail_status, name='get_engagement_detail_status'),
    path('get_accounting/', get_accounting, name='get_accounting'),
    path('get_tax/', get_tax, name='get_tax'),
    path('get_payroll/', get_payroll, name='get_payroll'),
    path('get_report/', get_report, name='get_report'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskcontrol/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.db import models
from taskcontrol.models import FileManage

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254)

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

taskcontrol/views.py
from django.shortcuts import render, redirect, get_object_or_404
from taskcontrol.models import *
from .forms import CustomUserCreationForm, CustomPasswordResetForm
from datetime import datetime, date, timedelta
from django.utils import timezone
from django.contrib import messages
from django.db import transaction
from django.utils.dateparse import parse_date
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseBadRequest, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.db.models import Max, Count, F, Subquery, Q, Case, When, Value, CharField, Prefetch
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from collections import Counter
from django.views.decorators.http import require_POST
from dateutil.relativedelta import relativedelta
from django.views.decorators.csrf import csrf_exempt
from django.db.models.functions import ExtractMonth, ExtractYear
import json


# Constants
STATUS_OPEN_JOB = ('OPEN_JOB', 'PENDING_CLIENT', 'REVIEW', 'IN_PROGRESS')
STATUS_DONE = ('DONE',)

#TODO Error404
def error_404_view(request, exception):
    return render(request, 'task/eror404.html', status=404)

#TODO Coding
def building_code(request):
    return render(request, 'task/coding.html')

#TODO Login
def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'เข้าสู่ระบบสำเร็จ')
            return redirect('taskcontrol:dashboard')
        else:
            messages.error(request, 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง')
    return render(request, 'accounts/login.html')

#TODO Logout
def logout_view(request):
    if request.user.is_authenticated:
        # last_login_time = request.user.last_login
        logout(request)
        messages.success(request, 'ออกจากระบบเรียบร้อย.')

        # if last_login_time is not None:
        #     current_time = datetime.now()
        #     time_difference = current_time - last_login_time

        #     if time_difference.total_seconds() > 3600:
        #         messages.success(request, 'ออกจากระบบ เนื่องจากไม่มีการใช้งานเกิน 1 ชั่วโมง.')
    return redirect('taskcontrol:login')

#TODO Others
def parse_date(date_string):
    if not date_string:
        return None
    try:
        return datetime.strptime(date_string, "%Y-%m-%d")
    except ValueError:
        print(f"Error parsing date string: {date_string}")
        return None

#TODO GetData
def get_districts(request):
    province_id = request.GET.get('province_id')
    district = District.objects.filter(province=province_id).all().values('id','name_th')
    return JsonResponse(list(district),safe=False)

def get_subdistricts(request):
    district_id = request.GET.get('district_id')
    subdistrict = Subdistrict.objects.filter(district=district_id).all().values('id', 'name_th', 'zipcode')
    return JsonResponse(list(subdistrict),safe=False)

def get_channel(request):
    channel_id = request.GET.get('channel_id')
    channel = Channel.objects.filter(id=channel_id).values('id', 'name')
    return JsonResponse(list(channel), safe=False)

def gen_engagement_code_auto(request):
    latest_job_code = Engagement.objects.aggregate(Max('job_code'))['job_code__max']

    # ตรวจสอบหาก latest_job_code เป็น None แล้วกำหนดให้เป็น '24-0001'
    if latest_job_code is not None:
        current_number = int(latest_job_code.split('-')[1]) + 1
    else:
        current_number = 1

    # ดึงปีปัจจุบัน
    current_year = datetime.now().year

    new_job_code = f'24-{current_number:04d}'

    return JsonResponse({'latest_job_code': new_job_code})

#TODO Client
@login_required
def client_list(request):
    clients_list = Client.objects.all().order_by('code')

    contacts = []
    for client in clients_list:
        first_contact = Contact.objects.filter(client_id=client.id).first()
        contacts.append(first_contact)

    return render(request, 'task/clients/client_list.html', {
        'clients_list': clients_list,
        'contacts': contacts,
    })

#TODO Record Client
@login_required
def record_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagement_all = Engagement.objects.filter(client_id=client_id).all()
    contact_all = Contact.objects.filter(client_id=client_id).all()
    return render(request, 'task/clients/record_client.html', {
        'client': client,
        'engagement_all':engagement_all,
        'contact_all':contact_all
    })

#TODO Client Detail
@login_required
def client_detail(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagements = Engagement.objects.filter(client_id=client_id).exclude(status='DONE').order_by('job_code')

    unique_engagements = []
    seen_job_codes = set()
    for engagement in engagements:
        if engagement.job_code not in seen_job_codes:
            unique_engagements.append(engagement)
            seen_job_codes.add(engagement.job_code)

    # Collect unique engagement types for each unique engagement
    engagement_data = []
    for engagement in unique_engagements:
        engagement_types = EngagementDetail.objects.filter(engagement=engagement).exclude(engagement__status='DONE').values_list('engagement_type__name_th', flat=True).distinct()
        engagement_data.append({
            'engagement': engagement,
            'types': list(set(engagement_types))  # Remove duplicates
        })

    contact_all = Contact.objects.filter(client_id=client_id)
    contacts = Contact.objects.all()
    subdistricts = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    districts = District.objects.values('id', 'name_th')
    provinces = Province.objects.all().order_by('name_th')
    register_types = RegisterType.objects.values('id', 'short_name', 'name_th', 'name_en')
    channels = Channel.objects.values('id', 'name')

    context = {
        'client': client,
        'engagement_data': engagement_data,
        'contact_all': contact_all,
        'contacts': contacts,
        'subdistricts': subdistricts,
        'districts': districts,
        'provinces': provinces,
        'register_types': register_types,
        'channels': channels,
    }
    return render(request, 'task/clients/client_detail.html', context)

#TODO Client Create
@login_required
def client_create(request):
    register_tax = None
    file = None
    contact = None
    client = None

    subdistrict = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    district = District.objects.values('id', 'name_th')
    province = Province.objects.values('id', 'name_th').order_by('name_th')
    register_types = RegisterType.objects.values('id','short_name','name_th','name_en')
    channels = Channel.objects.values('id','name')

    if request.method == 'POST':
        c_code = request.POST.get('c_code', '')
        c_company_name = request.POST.get('c_company_name', '')
        c_tax_id = request.POST.get('c_tax_id', '')
        c_address = request.POST.get('c_address')
        c_address2 = request.POST.get('c_address2')
        c_province = request.POST.get('c_province')
        c_district = request.POST.get('c_district')
        c_subdistrict = request.POST.get('c_subdistrict')
        c_channel = request.POST.get('c_channel')
        c_detail = request.POST.get('c_detail')
        c_status = request.POST.get('c_status')
        c_status = True if c_status == 'on' else False
        c_create_client_date = request.POST.get('c_create_client_date', '')

        r_company = request.POST.get('r_company') == 'True'
        r_company_date = request.POST.get('r_company_date')
        r_company_period_date = request.POST.get('r_company_period_date')
        r_vat = request.POST.get('r_vat') == 'True'
        r_vat_date = request.POST.get('r_vat_date')
        r_sbt = request.POST.get('r_sbt') == 'True'
        r_sbt_date = request.POST.get('r_sbt_date')
        r_sso = request.POST.get('r_sso') == 'True'
        r_sso_date = request.POST.get('r_sso_date')
        r_dbd_e_filling = request.POST.get('r_dbd_e_filling') == 'True'
        r_dbd_e_filling_date = request.POST.get('r_dbd_e_filling_date')
        
        date_c_create_client_date = parse_date(c_create_client_date)

        c_r_company_date = parse_date(r_company_date)
        c_r_company_period_date = parse_date(r_company_period_date)
        c_r_vat_date = parse_date(r_vat_date)
        c_r_sbt_date = parse_date(r_sbt_date)
        c_r_sso_date = parse_date(r_sso_date)
        c_r_dbd_e_filling_date = parse_date(r_dbd_e_filling_date)

        company_address = AddressBase(
            address = c_address,
            address2 = c_address2,
            province=Province.objects.filter(id=c_province).first(),
            district=District.objects.filter(id=c_district).first(),
            subdistrict=Subdistrict.objects.filter(id=c_subdistrict).first(),
        )
        company_address.save()

        client = Client(
            code=c_code,
            company_name=c_company_name,
            tax_id=c_tax_id,
            create_client_date = date_c_create_client_date,
            channel=Channel.objects.filter(id=c_channel).first(),
            detail=c_detail,
            status=c_status,
            register_tax=register_tax,
            company_address = company_address,
            create_by=request.user,
        )
        client.save()

        register_tax = RegisterTax(
            vat=r_vat,
            vat_date=c_r_vat_date,
            sbt=r_sbt,
            sbt_date=c_r_sbt_date,
            sso=r_sso,
            sso_date=c_r_sso_date,
            dbd_e_filling=r_dbd_e_filling,
            dbd_e_filling_date=c_r_dbd_e_filling_date,

taskcontrol/templates/task/setting/engagement_category.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.bootstrap5.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.2/css/responsive.bootstrap5.css">

{% extends 'task/index.html' %} 
{% block content %}

<style>
    th, td {
        font-size: 14px;
        vertical-align: middle;
    }

    th {
        font-size: 13.5px;
    }

    .table-sm>:not(caption)>*>* {
        padding: 0.5rem 0.5rem;
    }
</style>

<div class="card">
    <div class="d-flex justify-content-end mt-2 mx-2">
        <div class="btn-group">
            <a href="{% url 'taskcontrol:manage_category' %}" class="btn btn-primary" aria-current="page"><i class="fa-solid fa-quote-left"></i> หมวดหมู่งาน</a>
            <a href="{% url 'taskcontrol:manage_type' %}" class="btn btn-outline-primary">ประเภทงาน <i class="fa-solid fa-quote-right"></i></a>
        </div>
   </div>
    <div class="card-body">
        <div class="row mb-2">
            <form id="add-category-form" method="post" action="{% url 'taskcontrol:manage_category' %}">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="category_name_th" class="form-label">หมวดหมู่งาน :</label>
                    <div class="col-4">
                        <input type="text" class="form-control" name="category_name_th" id="category_name_th" required />
                    </div>
                    <div class="col-4 text-start">
                        <button type="submit" class="btn btn-outline-success">
                            <i class="fa-solid fa-plus"></i> เพิ่ม
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="table-responsive mb-3">
            <table id="category-table" class="table table-sm table-bordered">
                <thead class="table-light">
                    <tr>
                        <th class="text-center" style="width: 5%;">#</th>
                        <th class="text-start">หมวดงาน</th>
                        <th class="text-center" style="width: 10%;"><i class="fa-solid fa-gears"></i></th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in engagement_categories %}
                    <tr data-category-id="{{ category.id }}">
                        <td class="text-center">{{ forloop.counter }}</td>
                        <td class="text-start">{{ category.name_th }}</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-outline-warning btn-sm edit-category-button" data-bs-toggle="modal" data-bs-target="#updateCategoryModal" data-category-id="{{ category.id }}">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </button>
                                <button type="button" class="btn btn-secondary btn-sm delete-category-button disabled" data-delete-url="{% url 'taskcontrol:delete_category' category_id=category.id %}">
                                    <i class="fa-solid fa-trash-can"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Categories Modal -->
<div class="modal fade" id="updateCategoryModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-dark fw-semibold"><i class="fa-solid fa-pen-to-square" style="color: #ffbc35;"></i>&nbsp;แก้ไขหมวดงาน :</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="edit-category-form" method="POST">
                    {% csrf_token %}
                    <input type="hidden" id="edit-category-id" name="category_id">
                    <div class="mb-3">
                        <label for="edit-name-th" class="form-label">ชื่อหมวดงาน:</label>
                        <input type="text" id="edit-name-th" name="new_category_name_th" class="form-control">
                    </div>
                    <div class="modal-footer text-end">
                        <button type="submit" class="btn btn-outline-warning">บันทึกแก้ไข</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.bootstrap5.js"></script>
<script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.js"></script>
<script src="https://cdn.datatables.net/responsive/3.0.2/js/responsive.bootstrap5.js"></script>

<script>
    $(document).ready(function() {
        const dataTable = $("#category-table").DataTable({
            "language": {
                "search": "ค้นหา",
                "lengthMenu": "แสดง _MENU_ รายการ",
                "info": "แสดง _START_ ถึง _END_ จากทั้งหมด _TOTAL_ รายการ",
                "paginate": {
                    "previous": "ก่อนหน้า",
                    "next": "ถัดไป"
                }
            }
        });

        // Event listener for delete category button
        $(".delete-category-button").on("click", function() {
            deleteCategory($(this));
        });

        // Event listener for edit category button
        $(".edit-category-button").on("click", function() {
            editCategory($(this));
        });

        // Event listener for submitting edit category form
        $("#edit-category-form").on("submit", function(event) {
            event.preventDefault();
            updateCategory($(this));
        });

        // Event listener for submitting add category form
        $("#add-category-form").on("submit", function(event) {
            event.preventDefault();
            addCategory($(this));
        });

        // Function to delete a category
        function deleteCategory(button) {
            if (confirm("ต้องการลบหมวดหมู่งานจริงหรือไม่?")) {
                var categoryId = button.closest("tr").data("category-id");
                var deleteUrl = "{% url 'taskcontrol:delete_category' category_id=0 %}".replace("0", categoryId);
                $.ajax({
                    type: 'POST',
                    url: deleteUrl,
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function() {
                        $('[data-category-id="' + categoryId + '"]').remove();
                        $('#updateCategoryModal').modal('hide');
                        location.reload();
                    },
                    error: function(xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            }
        }

        // Function to edit a category
        function editCategory(button) {
            var categoryRow = button.closest("tr");
            var categoryId = categoryRow.data("category-id");
            var nameTH = categoryRow.find("td:eq(1)").text();

            $("#edit-category-id").val(categoryId);
            $("#edit-name-th").val(nameTH);
            $('#updateCategoryModal').modal('show');
        }

        // Function to update a category
        function updateCategory(form) {
            var formData = form.serialize();
            var categoryId = $("#edit-category-id").val();
            var updateUrl = "{% url 'taskcontrol:update_category' category_id=0 %}".replace("0", categoryId);
            $.ajax({
                type: 'POST',
                url: updateUrl,
                data: formData,
                success: function() {
                    $('#updateCategoryModal').modal('hide');
                    location.reload();
                },
                error: function(xhr, status, error) {
                    console.error(xhr.responseText);
                }
            });
        }

        // Function to add a new category
        function addCategory(form) {
            var formData = form.serialize();
            $.ajax({
                type: 'POST',
                url: "{% url 'taskcontrol:manage_category' %}",
                data: formData,
                success: function() {
                    form.trigger("reset");
                    location.reload(); // Reload the page after successful addition
                },
                error: function(xhr, status, error) {
                    console.error(xhr.responseText);
                }
            });
        }
    });
</script>

{% endblock content %}

taskcontrol/templates/task/setting/register_type copy.html
{% extends 'task/index.html' %} 
{% block content %}
<div class="row">
    <div class="card w-100">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <form id="createRegisterTypeForm" method="post" action="{% url 'taskcontrol:manage_register_type' %}">
                        {% csrf_token %}
                        <div class="h5 pb-2 mb-4 text-primary fw-semibold border-bottom border-primary">
                            เพิ่มข้อมูลจดทะเบียนใหม่
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <label for="short_name" class="form-label">ชื่อย่อ:</label>
                                <input type="text" class="form-control" id="short_name" name="short_name">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <label for="name_th" class="form-label fw-semibold">ชื่อเต็มภาษาไทย:</label>
                                <input type="text" class="form-control" id="name_th" name="name_th">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <label for="name_en" class="form-label fw-semibold">ชื่อเต็มภาษาอังกฤษ:</label>
                                <input type="text" class="form-control" id="name_en" name="name_en">
                            </div>
                        </div>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                            <button type="submit" class="btn btn-primary">เพิ่ม</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-7">
                    <div class="table-responsive">
                        <table class="table mt-2">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>ชื่อย่อ</th>
                                    <th>ชื่อเต็มภาษาไทย</th>
                                    <th>ชื่อเต็มภาษาอังกฤษ</th>
                                    <th>แก้ไข</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for r in register_type_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ r.short_name }}</td>
                                    <td>{{ r.name_th }}</td>
                                    <td>{{ r.name_en }}</td>
                                    <td>
                                        <a href="{% url 'taskcontrol:delete_register_type' register_type_id=r.id %}" class="delete-register-type" data-register-type-id="{{ r.id }}">
                                             <i class="fa-solid fa-circle-xmark fa-lg" style="color: #f64c4c;"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
     $(".delete-register-type").on("click", function() {
          var registertypeId = $(this).data("register-type-id");
          if (confirm("ต้องการลบรายการนี้?")) {
               var createregistertypetUrl = "{% url 'taskcontrol:delete_register_type' register_type_id=0 %}".replace("0", registertypeId);

              $.ajax({
                  type: 'POST',
                  url: createregistertypetUrl,
                  data: {
                      csrfmiddlewaretoken: '{{ csrf_token }}',
                  },
                  success: function() {
                      location.reload();
                  },
                  error: function(xhr, status, error) {
                      console.error(xhr.responseText);
                  }
              });
          }
      });
</script>
{% endblock content %}