pconnectacc/urls.py
from django.contrib import admin
from django.urls import path, include
from taskcontrol import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task-control/', include('taskcontrol.urls')),
]

taskcontrol/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

app_name = "taskcontrol"

handler404 = 'taskcontrol.views.error_404_view'

urlpatterns = [
    path('eror404/', error_404_view, name='eror404'),
    path('coding/', building_code, name='building_code'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    # path('test/', testpage, name='testpage'),
    path('get_districts/', get_districts, name='GetDistrict'),
    path('get_subdistricts/', get_subdistricts, name='GetSubdistrict'),
    path('gen_engagement_code_auto/', gen_engagement_code_auto, name='get_latest_job_code'),
    path('get_channel/', get_channel, name='get_channel'),

    path('get_engagement_type/', get_engagement_type, name='get_engagement_type'),
    path('api/get_engagement_details/', get_engagement_details, name='get_engagement_details'),



    path('client/list/', client_list, name='client_list'),
    path('client/<int:client_id>/', record_client, name='record_client'),

    path('client/create/', client_create, name='client_create'),
    path('client/detail/<int:client_id>/', client_detail, name='client_detail'),
    path('client/update/<int:client_id>/', client_update, name='client_update'),
    path('client/delete/<int:client_id>/', client_delete, name='client_delete'),

    path('client/contact_create/<int:client_id>/', create_contact, name='create_contact'),
    path('client/contact_delete/<int:contact_id>/', delete_contact, name='delete_contact'),

    path('client/password/<int:client_id>/', password_list, name='password_list'),
    path('client/password_create/<int:client_id>/', create_password, name='create_password'),
    path('client/password_update/<int:password_id>/', update_password, name='update_password'),
    path('client/password_delete/<int:password_id>/', delete_password, name='delete_password'),

    path('client/file_list/<int:client_id>/', file_client_list, name='file_client_list'),
    path('client/file_create/<int:client_id>/', file_client_create, name='file_client_create'),
    path('client/file_delete/<int:file_id>/', file_client_delete, name='file_client_delete'),
    path('client/file_client_download_file/<int:file_id>/', file_client_download_file, name='file_client_download_file'),
    path('client/file_client_download_image/<int:image_id>/', file_client_download_image, name='file_client_download_image'),

    path('engagement/list/', engagement_list, name='engagement_list'),
    path('engagement/create/', engagement_create, name='engagement_create'),
    path('engagement/<int:engagement_id>/', record_engagement, name='record_engagement'),
    path('engagement/detail/<int:engagement_id>/', engagement_detail, name='engagement_detail'),
    path('engagement/update/<int:engagement_id>/', engagement_update, name='engagement_update'),
    path('engagement/delete/<int:engagement_id>/', engagement_delete, name='engagement_delete'),

    path('engagement/detail_job/<int:engagement_id>/', engagement_job, name='engagement_job'),
    path('engagement/detail_job/create/<int:engagement_id>/', engagement_job_create, name='engagement_job_create'),
    path('engagement/detail_job/delete/<int:engagement_job_id>/', engagement_job_delete, name='engagement_job_delete'),

    path('engagement/file_list/<int:engagement_id>/', file_engagement_list, name='file_engagement_list'),
    path('engagement/file_create/<int:engagement_id>/', file_engagement_create, name='file_engagement_create'),
    path('engagement/file_delete/<int:file_id>/', file_engagement_delete, name='file_engagement_delete'),
    path('engagement/file_client_download_file/<int:file_id>/', download_file_engagement, name='download_file_engagement'),
    path('engagement/file_client_download_image/<int:image_id>/', download_image_engagement, name='download_image_engagement'),

    path('manage_category/', manage_category, name='manage_category'),
    path('manage_category/update/<int:category_id>/', update_category, name='update_category'),
    path('manage_category/delete/<int:category_id>/', delete_category, name='delete_category'),

    path('manage_type/', manage_type, name='manage_type'),
    path('manage_type/update/<int:type_id>/', update_type, name='update_type'),
    path('manage_type/delete/<int:type_id>/', delete_type, name='delete_type'),

    path('manage_channel/', manage_channel, name='manage_channel'),
    path('manage_channel/update/<int:channel_id>/', update_channel, name='update_channel'),
    path('manage_channel/delete/<int:channel_id>/', delete_channel, name='delete_channel'),

    path('manage_register_type/', manage_register_type, name='manage_register_type'),
    path('manage_register_type/update/<int:register_type_id>/', update_register_type, name='update_register_type'),
    path('manage_register_type/delete/<int:register_type_id>/', delete_register_type, name='delete_register_type'),

    path('kanban_board/', kanban_board, name='kanban_board'),
    path('update_engagement_detail_status', update_engagement_detail_status, name='update_engagement_detail_status'),
    path('update_task_status', update_task_status, name='update_task_status'),
    path('add_new_task/', add_new_task, name='add_new_task'),

    path('kanban_board_filter/', kanban_board_filter, name='kanban_board_filter'),
    path('get_status_counts/', get_status_counts, name='get_status_counts'),
    path('update_near_deadline/', update_near_deadline, name='update_near_deadline'),
    path('get_date_deadlines/', get_date_deadlines, name='get_date_deadlines'),

    
    path('update_engagement_detail_comment', update_engagement_detail_comment, name='update_engagement_detail_comment'),
    path('search_filter_engagement_details/', search_filter_engagement_details, name='search_filter_engagement_details'),
    path('get_filter_engagement_details/', get_filter_engagement_details, name='get_filter_engagement_details'),

    path('dashboard/', dashboard, name='dashboard'),
    path('api/engagement-details/', get_engagement_detail_dashboard, name='get_engagement_detail_dashboard'),
    # path('search_datatable/', search_datatable, name='search_datatable'),
    path('get_engagement_detail_status/', get_engagement_detail_status, name='get_engagement_detail_status'),
    path('get_accounting/', get_accounting, name='get_accounting'),
    path('get_tax/', get_tax, name='get_tax'),
    path('get_payroll/', get_payroll, name='get_payroll'),
    path('get_report/', get_report, name='get_report'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskcontrol/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.db import models
from taskcontrol.models import FileManage

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254)

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

taskcontrol/views.py
from django.shortcuts import render, redirect, get_object_or_404
from taskcontrol.models import *
from .forms import CustomUserCreationForm, CustomPasswordResetForm
from datetime import datetime, date, timedelta
from django.utils import timezone
from django.contrib import messages
from django.db import transaction
from django.utils.dateparse import parse_date
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseBadRequest, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.db.models import Max, Count, F, Subquery, Q, Case, When, Value, CharField, Prefetch
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from collections import Counter
from django.views.decorators.http import require_POST
from dateutil.relativedelta import relativedelta
from django.views.decorators.csrf import csrf_exempt
from django.db.models.functions import ExtractMonth, ExtractYear
import json


# Constants
STATUS_OPEN_JOB = ('OPEN_JOB', 'PENDING_CLIENT', 'REVIEW', 'IN_PROGRESS')
STATUS_DONE = ('DONE',)

#TODO Error404
def error_404_view(request, exception):
    return render(request, 'task/eror404.html', status=404)

#TODO Coding
def building_code(request):
    return render(request, 'task/coding.html')

#TODO Login
def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'เข้าสู่ระบบสำเร็จ')
            return redirect('taskcontrol:dashboard')
        else:
            messages.error(request, 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง')
    return render(request, 'accounts/login.html')

#TODO Logout
def logout_view(request):
    if request.user.is_authenticated:
        # last_login_time = request.user.last_login
        logout(request)
        messages.success(request, 'ออกจากระบบเรียบร้อย.')

        # if last_login_time is not None:
        #     current_time = datetime.now()
        #     time_difference = current_time - last_login_time

        #     if time_difference.total_seconds() > 3600:
        #         messages.success(request, 'ออกจากระบบ เนื่องจากไม่มีการใช้งานเกิน 1 ชั่วโมง.')
    return redirect('taskcontrol:login')

#TODO Others
def parse_date(date_string):
    if not date_string:
        return None
    try:
        return datetime.strptime(date_string, "%Y-%m-%d")
    except ValueError:
        print(f"Error parsing date string: {date_string}")
        return None

#TODO GetData
def get_districts(request):
    province_id = request.GET.get('province_id')
    district = District.objects.filter(province=province_id).all().values('id','name_th')
    return JsonResponse(list(district),safe=False)

def get_subdistricts(request):
    district_id = request.GET.get('district_id')
    subdistrict = Subdistrict.objects.filter(district=district_id).all().values('id', 'name_th', 'zipcode')
    return JsonResponse(list(subdistrict),safe=False)

def get_channel(request):
    channel_id = request.GET.get('channel_id')
    channel = Channel.objects.filter(id=channel_id).values('id', 'name')
    return JsonResponse(list(channel), safe=False)

def gen_engagement_code_auto(request):
    latest_job_code = Engagement.objects.aggregate(Max('job_code'))['job_code__max']

    # ตรวจสอบหาก latest_job_code เป็น None แล้วกำหนดให้เป็น '24-0001'
    if latest_job_code is not None:
        current_number = int(latest_job_code.split('-')[1]) + 1
    else:
        current_number = 1

    # ดึงปีปัจจุบัน
    current_year = datetime.now().year

    new_job_code = f'24-{current_number:04d}'

    return JsonResponse({'latest_job_code': new_job_code})

#TODO Client
@login_required
def client_list(request):
    clients_list = Client.objects.all().order_by('code')

    contacts = []
    for client in clients_list:
        first_contact = Contact.objects.filter(client_id=client.id).first()
        contacts.append(first_contact)

    return render(request, 'task/clients/client_list.html', {
        'clients_list': clients_list,
        'contacts': contacts,
    })

#TODO Record Client
@login_required
def record_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagement_all = Engagement.objects.filter(client_id=client_id).all()
    contact_all = Contact.objects.filter(client_id=client_id).all()
    return render(request, 'task/clients/record_client.html', {
        'client': client,
        'engagement_all':engagement_all,
        'contact_all':contact_all
    })

#TODO Client Detail
@login_required
def client_detail(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    engagements = Engagement.objects.filter(client_id=client_id).exclude(status='DONE').order_by('job_code')

    unique_engagements = []
    seen_job_codes = set()
    for engagement in engagements:
        if engagement.job_code not in seen_job_codes:
            unique_engagements.append(engagement)
            seen_job_codes.add(engagement.job_code)

    # Collect unique engagement types for each unique engagement
    engagement_data = []
    for engagement in unique_engagements:
        engagement_types = EngagementDetail.objects.filter(engagement=engagement).exclude(engagement__status='DONE').values_list('engagement_type__name_th', flat=True).distinct()
        engagement_data.append({
            'engagement': engagement,
            'types': list(set(engagement_types))  # Remove duplicates
        })

    contact_all = Contact.objects.filter(client_id=client_id)
    contacts = Contact.objects.all()
    subdistricts = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    districts = District.objects.values('id', 'name_th')
    provinces = Province.objects.all().order_by('name_th')
    register_types = RegisterType.objects.values('id', 'short_name', 'name_th', 'name_en')
    channels = Channel.objects.values('id', 'name')

    context = {
        'client': client,
        'engagement_data': engagement_data,
        'contact_all': contact_all,
        'contacts': contacts,
        'subdistricts': subdistricts,
        'districts': districts,
        'provinces': provinces,
        'register_types': register_types,
        'channels': channels,
    }
    return render(request, 'task/clients/client_detail.html', context)

#TODO Client Create
@login_required
def client_create(request):
    register_tax = None
    file = None
    contact = None
    client = None

    subdistrict = Subdistrict.objects.values('id', 'name_th', 'zipcode')
    district = District.objects.values('id', 'name_th')
    province = Province.objects.values('id', 'name_th').order_by('name_th')
    register_types = RegisterType.objects.values('id','short_name','name_th','name_en')
    channels = Channel.objects.values('id','name')

    if request.method == 'POST':
        c_code = request.POST.get('c_code', '')
        c_company_name = request.POST.get('c_company_name', '')
        c_tax_id = request.POST.get('c_tax_id', '')
        c_address = request.POST.get('c_address')
        c_address2 = request.POST.get('c_address2')
        c_province = request.POST.get('c_province')
        c_district = request.POST.get('c_district')
        c_subdistrict = request.POST.get('c_subdistrict')
        c_channel = request.POST.get('c_channel')
        c_detail = request.POST.get('c_detail')
        c_status = request.POST.get('c_status')
        c_status = True if c_status == 'on' else False
        c_create_client_date = request.POST.get('c_create_client_date', '')

        r_company = request.POST.get('r_company') == 'True'
        r_company_date = request.POST.get('r_company_date')
        r_company_period_date = request.POST.get('r_company_period_date')
        r_vat = request.POST.get('r_vat') == 'True'
        r_vat_date = request.POST.get('r_vat_date')
        r_sbt = request.POST.get('r_sbt') == 'True'
        r_sbt_date = request.POST.get('r_sbt_date')
        r_sso = request.POST.get('r_sso') == 'True'
        r_sso_date = request.POST.get('r_sso_date')
        r_dbd_e_filling = request.POST.get('r_dbd_e_filling') == 'True'
        r_dbd_e_filling_date = request.POST.get('r_dbd_e_filling_date')
        
        date_c_create_client_date = parse_date(c_create_client_date)

        c_r_company_date = parse_date(r_company_date)
        c_r_company_period_date = parse_date(r_company_period_date)
        c_r_vat_date = parse_date(r_vat_date)
        c_r_sbt_date = parse_date(r_sbt_date)
        c_r_sso_date = parse_date(r_sso_date)
        c_r_dbd_e_filling_date = parse_date(r_dbd_e_filling_date)

        company_address = AddressBase(
            address = c_address,
            address2 = c_address2,
            province=Province.objects.filter(id=c_province).first(),
            district=District.objects.filter(id=c_district).first(),
            subdistrict=Subdistrict.objects.filter(id=c_subdistrict).first(),
        )
        company_address.save()

        client = Client(
            code=c_code,
            company_name=c_company_name,
            tax_id=c_tax_id,
            create_client_date = date_c_create_client_date,
            channel=Channel.objects.filter(id=c_channel).first(),
            detail=c_detail,
            status=c_status,
            register_tax=register_tax,
            company_address = company_address,
            create_by=request.user,
        )
        client.save()

        register_tax = RegisterTax(
            vat=r_vat,
            vat_date=c_r_vat_date,
            sbt=r_sbt,
            sbt_date=c_r_sbt_date,
            sso=r_sso,
            sso_date=c_r_sso_date,
            dbd_e_filling=r_dbd_e_filling,
            dbd_e_filling_date=c_r_dbd_e_filling_date,

taskcontrol/templates/task/404 copy.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap')

        body {
            font-family: "Roboto Mono", monospace;
        }

        .page_404 {
            padding: 40px 0;
            background: #fff;
            font-family: "Roboto Mono", monospace;
        }

        .page_404 img {
            width: 100%;
        }

        .four_zero_four_bg {
            background-image: url(https://cdn.dribbble.com/users/285475/screenshots/2083086/dribbble_1.gif);
            height: 400px;
            background-position: center;
        }


        .four_zero_four_bg h1 {
            font-size: 80px;
            font-weight: 900;
        }

        .four_zero_four_bg h3 {
            font-size: 80px;
        }

        .link_404 {
            color: #fff !important;
            padding: 10px 20px;
            background: #39ac31;
            margin: 20px 0;
            display: inline-block;
        }

        .contant_box_404 {
            margin-top: -50px;
        }
    </style>
</head>

<body>
    <section class="page_404">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    <div class="col-sm-10 col-sm-offset-1  text-center">
                        <div class="four_zero_four_bg">
                            <h1 class="text-center">Oops! 404</h1>

                        </div>

                        <div class="contant_box_404">
                            <h3 class="h2">Look like you're lost</h3>

                            <p>the page you are looking for not available!</p>

                            <a href="{% url 'taskcontrol:dashboard' %}" aria-expanded="false" class="link_404"><i class="fa-solid fa-house-chimney"></i> Go to Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

taskcontrol/templates/task/all.html
{{ client_list.code }}
{{ client_list.company_name }}

taskcontrol/templates/task/coding.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coding...</title>
    <link rel="icon" href="{% static 'icon/coding.svg' %}" type="image/svg+xml">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.4/components/error-404s/error-404-1/assets/css/error-404-1.css">
</head>

<body>
    <section class="py-3 py-md-5 min-vh-100 d-flex justify-content-center align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="text-center">
                        <h2 class="d-flex justify-content-center align-items-center gap-2 mb-4">
                            <span class="display-1 fw-bold">C</span>
                            <!-- <i class="bi bi-exclamation-circle-fill text-danger display-4"></i> -->
                            <!-- <i class="bi bi-bug-fill text-danger display-4"></i> -->
                            <i class="bi bi-code-square text-danger display-4"></i>
                            <span class="display-1 fw-bold">ding</span>
                        </h2>
                        <p class="mb-5"><i class="bi bi-gear-wide-connected"></i> We are in process of solving that problem.</p>
                        <a class="btn btn-dark rounded-pill px-5 fs-6 m-0" href="{% url 'taskcontrol:dashboard' %}" role="button"> Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

taskcontrol/templates/task/navbar.html
{% load static %}
<link rel="icon" href="{% static 'assets/images/logos/connectacc1.png' %}" type="image/png">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>



<aside class="left-sidebar">
    <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
            <i class="fa-brands fa-connectdevelop fa-xl" style="color: #327af5;"></i>
            <h5 style="margin: 0;">Account <br> Tasks Controller</h5>
            <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                <i class="fa-solid fa-xmark fa-xl"></i>
            </div>
        </div>
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <ul id="sidebarnav">
                <li class="nav-small-cap">
                    <span class="hide-menu">Home</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'taskcontrol:dashboard' %}" aria-expanded="false">
                        <span><i class="fa-solid fa-chart-pie"></i></span>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'taskcontrol:client_list' %}" aria-expanded="false">
                        <span><i class="fa-solid fa-users"></i></span>
                        <span class="hide-menu">Clients</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'taskcontrol:engagement_list' %}" aria-expanded="false">
                        <span><i class="fa-solid fa-box-archive"></i></span>
                        <span class="hide-menu">Engagement</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'taskcontrol:kanban_board' %}" aria-expanded="false">
                        <span><i class="fa-solid fa-list-check"></i></span>
                        <span class="hide-menu">Tasks Control</span>
                    </a>
                </li>
                <li class="nav-small-cap">
                    <span class="hide-menu">Setting</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'taskcontrol:setting' %}" aria-expanded="false">
                        <span>
                            <i class="fa-solid fa-gears"></i>
                        </span>
                        <span class="hide-menu">Setting</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="#" aria-expanded="false">
                        <span>
                            <i class="fa-solid fa-user-gear"></i>
                        </span>
                        <span class="hide-menu">User Manager</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

<header class="app-header fixed-top">
    <nav class="navbar navbar-expand-lg">
        <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                    <i class="fa-solid fa-bars"></i>
                </a>
            </li>
        </ul>
        <i class="fa-solid fa-seedling" style="color: #1ebe30;"></i>&nbsp;&nbsp;<span class="fw-semibold">ยินดีต้อนรับ,
            คุณ{{ user.first_name }} </span>
        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">

            <li class="nav-item">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop1" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    <i class="fa-regular fa-bell"></i>
                    <div class="notification bg-primary rounded-circle"></div>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                        <i class="fa-solid fa-circle fa-2xs" style="color: #FFD43B;"></i>
                        <span class="">ข้อความ 1</span>
                    </a>
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                        <i class="fa-solid fa-circle fa-2xs" style="color: #FFD43B;"></i>
                        <span class="">ข้อความ 2</span>
                    </a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    <i class="fa-solid fa-circle-user fa-lg"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                    <div class="message-body">
                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                            <i class="fa-solid fa-user"></i>
                            <p class="mb-0 fs-3">โปรไฟล์</p>
                        </a>
                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                            <i class="fa-solid fa-circle-info"></i>
                            <p class="mb-0 fs-3">คู่มือการใช้งาน</p>
                        </a>
                        <a href="#" aria-expanded="false"
                            class="btn btn-outline-danger mx-3 mt-2 d-block"><i
                                class="fa-solid fa-right-from-bracket"></i> ออกจากระบบ</a>
                    </div>
                </div>
            </li>
        </ul>
    </nav>
</header>